backend:
  name: git-gateway
  branch: main # IMPORTANT: Replace 'main' with your GitHub repository's default branch (e.g., 'master' if applicable)

media_folder: "assets/uploads" # Path to the folder where uploaded media (images) will be stored
public_folder: "/assets/uploads" # The public path to the media folder

collections:
  - name: "posts" # A unique identifier for this content collection
    label: "Mindful Moments Posts" # The name displayed in the CMS UI
    folder: "posts" # IMPORTANT: Path to the folder where your Markdown files will be stored in your repo
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template for new posts (e.g., 2025-07-24-my-new-post.md)
    fields: # The fields for each post entry in the CMS
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
